### ISSUE TITLE
ToDo:

### ISSUE THREAD

**Issue by Lylythii** [Lylythii/TFCPlus-Automated-Bellows#2]
- [ ] CraftTweaker Support
- [ ] Update Texture Assets
- [ ] NEI Integration
- [ ] Cross-Addon Integrations
- [ ] Fix Shields
- [ ] Allow Fuelling Boilers using *any* fluid container (not just Wooden Buckets of Fresh Water) & automation via pipes.
- [ ] Allow filling Pottery Kiln & Pottery Kiln Chambers with fuel/pottery automatically via hoppers/pipes/other item transport methods.
